ALTER TABLE tb_users DROP CONSTRAINT IF EXISTS tb_users_role_check;

ALTER TABLE tb_users
ALTER COLUMN role TYPE VARCHAR(50)

USING CASE role
WHEN 0 THEN 'ROLE_USER'
WHEN 1 THEN 'ROLE_ADMIN'
ELSE 'USER'
END;